# Generated by Django 5.1.1 on 2024-10-09 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seller'),
        ('products', '0020_alter_review_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('orders', models.ManyToManyField(related_name='orders', to='products.order')),
                ('products', models.ManyToManyField(related_name='products', to='products.products')),
                ('reviews', models.ManyToManyField(related_name='reviews', to='products.review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
