# Generated by Django 5.1.1 on 2024-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
        ('products', '0020_alter_review_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='products.order'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.products'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='images/default.jpg'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews', to='products.review'),
        ),
    ]
