# Generated by Django 5.1.1 on 2024-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_orders_alter_profile_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image/default.webp', null=True, upload_to='profile_pictures/'),
        ),
    ]
