# Generated by Django 5.1.1 on 2024-10-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='shop_name',
        ),
    ]
