# Generated by Django 5.1.1 on 2024-09-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
