# Generated by Django 5.1.1 on 2024-09-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_orderitem_user_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Categorry',
            field=models.CharField(choices=[('Fashion & Accessories', 'Fashion & Accessories'), ('Electronics & Gadgets', 'Electronics'), ('Home & Living', 'Home & Living'), ('Health & Beauty', 'Health & Beauty'), ('Toys & Kids', 'Toys & Kids'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Automotive & Tools', 'Automotive'), ('Books & Audible', 'Books & Audible'), ('Arts & Crafts', 'Arts & Crafts'), ('Travel & Luggage', 'Travel & Luggage'), ('Office & stationery', 'Office & stationery'), ('Pet Supplies', 'Pet Supplies'), ('Grocery', 'Grocery')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
