# Generated by Django 5.1.1 on 2024-09-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
