# Generated by Django 5.1.1 on 2024-09-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
